### PR TITLE
WHY IS THERE A DISCORD WEB HOOK????

### PR DESCRIPTION
**Pull request by master7720**

### CODE REVIEW

**Comment by Phantom568** [comment]
Why'd you make a pull request

**Comment by master7720** [comment]
i am pooping rn

**Comment by Phantom568** [comment]
Ok but anyways the webhook is so we can see alerts from our discord server it's so the members can see updates. https://i.imgur.com/qYQQG1B.png as seen in this picture

**Comment by TechAle** [comment]
The webhook 
1) Is down
2) Was for the irc
Like, take a look at the name lol, smort

**Pull request closed without merging**
