### PR TITLE
dis sum stuff

### PR DESCRIPTION
**Pull request by master7720**

### CODE REVIEW

**Comment by master7720** [comment]
i am black

**Comment by TechAle** [comment]
It's the worst pull request i have ever seen lol, go away dont make another pr

**Comment by master7720** [comment]
i am so good!!!!

**Comment by master7720** [comment]
come one accept the pr!!

**Comment by TechAle** [comment]
I decide what to add or not in gs++ and, if i find your things not serious, i wont accept them. If you want to create random things, just fork and work on your work

**Comment by master7720** [comment]
!!!!1!1!!!!!!1111!

**Comment by master7720** [comment]
you know that i am joking right?

**Comment by TechAle** [comment]
But i'm not

**Pull request closed without merging**
